services:
    react-web:
        working_dir: /app
        build: .
        stdin_open: true
        ports:
            - "127.0.0.1:3100:3100"
        volumes:
            - .:/app
            - /app/node_modules
        command: npm run dev
